export const SET_PICKUP_SPOT = 'SET_PICKUP_SPOT';

export const SET_DROPOFF_SPOT = 'SET_DROPOFF_SPOT';

export const SHOW_PICKUP_SPOT = 'SHOW_PICKUP_SPOT';

export const SHOW_DROPOFF_SPOT = 'SHOW_DROPOFF_SPOT';

export const CREATE_JOB = 'CREATE_JOB';

export const PICKUP_ADDRESS_ERROR = 'PICKUP_ADDRESS_ERROR';

export const DROPOFF_ADDRESS_ERROR = 'DROPOFF_ADDRESS_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
